///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADC_AUTO_Testing.WebPages.LoginPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_LoginPage_Validate_UI recording.
    /// </summary>
    [TestModule("e6796ccb-bb01-400a-b518-b87010f3de8c", ModuleType.Recording, 1)]
    public partial class Open_LoginPage_Validate_UI : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repository.
        /// </summary>
        public static ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repo = ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository.Instance;

        static Open_LoginPage_Validate_UI instance = new Open_LoginPage_Validate_UI();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_LoginPage_Validate_UI()
        {
            var_SubDomain = "https://boris12.onelogin.com/login";
            var_Browser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_LoginPage_Validate_UI Instance
        {
            get { return instance; }
        }

#region Variables

        string _var_SubDomain;

        /// <summary>
        /// Gets or sets the value of variable var_SubDomain.
        /// </summary>
        [TestVariable("f38268ec-d9d1-4c00-8826-12b98c40bd69")]
        public string var_SubDomain
        {
            get { return _var_SubDomain; }
            set { _var_SubDomain = value; }
        }

        string _var_Browser;

        /// <summary>
        /// Gets or sets the value of variable var_Browser.
        /// </summary>
        [TestVariable("52343ce6-8c27-4fd2-b86d-9a1b00a7e7e4")]
        public string var_Browser
        {
            get { return _var_Browser; }
            set { _var_Browser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $var_SubDomain with browser specified by variable $var_Browser in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser(var_SubDomain, var_Browser, "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OneLogin.LoginPage.UserPassword'.", repo.OneLogin.LoginPage.UserPasswordInfo, new RecordItemIndex(1));
            Validate.Exists(repo.OneLogin.LoginPage.UserPasswordInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OneLogin.LoginPage.UserEmail'.", repo.OneLogin.LoginPage.UserEmailInfo, new RecordItemIndex(2));
            Validate.Exists(repo.OneLogin.LoginPage.UserEmailInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Width='80') on item 'OneLogin.LoginPage.Logo'.", repo.OneLogin.LoginPage.LogoInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.OneLogin.LoginPage.LogoInfo, "Width", "80");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Log in') on item 'OneLogin.LoginPage.UserSubmit'.", repo.OneLogin.LoginPage.UserSubmitInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.OneLogin.LoginPage.UserSubmitInfo, "Value", "Log in");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OneLogin.LoginPage.ForgotPassword'.", repo.OneLogin.LoginPage.ForgotPasswordInfo, new RecordItemIndex(5));
            Validate.Exists(repo.OneLogin.LoginPage.ForgotPasswordInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OneLogin.LoginPage.Help'.", repo.OneLogin.LoginPage.HelpInfo, new RecordItemIndex(6));
            Validate.Exists(repo.OneLogin.LoginPage.HelpInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
