///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AD_Auto_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AD_Auto_TestingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("209b5892-73e4-4a1c-a799-5efc0ce843bc")]
    public partial class AD_Auto_TestingRepository : RepoGenBaseFolder
    {
        static AD_Auto_TestingRepository instance = new AD_Auto_TestingRepository();

        /// <summary>
        /// Gets the singleton class instance representing the AD_Auto_TestingRepository element repository.
        /// </summary>
        [RepositoryFolder("209b5892-73e4-4a1c-a799-5efc0ce843bc")]
        public static AD_Auto_TestingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AD_Auto_TestingRepository() 
            : base("AD_Auto_TestingRepository", "/", null, 0, false, "209b5892-73e4-4a1c-a799-5efc0ce843bc", ".\\RepositoryImages\\AD_Auto_TestingRepository209b5892.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("209b5892-73e4-4a1c-a799-5efc0ce843bc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class AD_Auto_TestingRepositoryFolders
    {
    }
#pragma warning restore 0436
}