///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADC_AUTO_Testing.WebPages.Menu1_USERS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_and_Verify_SubMenu_Directories recording.
    /// </summary>
    [TestModule("735c06a1-62a9-463f-ae9e-24bba83a3ca6", ModuleType.Recording, 1)]
    public partial class Open_and_Verify_SubMenu_Directories : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repository.
        /// </summary>
        public static ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repo = ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository.Instance;

        static Open_and_Verify_SubMenu_Directories instance = new Open_and_Verify_SubMenu_Directories();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_and_Verify_SubMenu_Directories()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_and_Verify_SubMenu_Directories Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OneLogin.LoginPage.BrandImage' at Center.", repo.OneLogin.LoginPage.BrandImageInfo, new RecordItemIndex(0));
            repo.OneLogin.LoginPage.BrandImage.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OneLogin.LoginPage.Users' at CenterLeft.", repo.OneLogin.LoginPage.UsersInfo, new RecordItemIndex(1));
            repo.OneLogin.LoginPage.Users.MoveTo(Location.CenterLeft);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.", new RecordItemIndex(2));
            Delay.Duration(100, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OneLogin.MainNavBar.SubMenu_Directories' at Center.", repo.OneLogin.MainNavBar.SubMenu_DirectoriesInfo, new RecordItemIndex(3));
            repo.OneLogin.MainNavBar.SubMenu_Directories.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'OneLogin.DirectoriesPage.NewDirectory'.", repo.OneLogin.DirectoriesPage.NewDirectoryInfo, new RecordItemIndex(4));
            Validate.Exists(repo.OneLogin.DirectoriesPage.NewDirectoryInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'OneLogin.LoginPage.BrandImage' at Center.", repo.OneLogin.LoginPage.BrandImageInfo, new RecordItemIndex(5));
            repo.OneLogin.LoginPage.BrandImage.MoveTo();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
