///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADC_AutoTesting
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ADC_AutoTestingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("95f67aba-6c58-4884-bb87-3897faf7a665")]
    public partial class ADC_AutoTestingRepository : RepoGenBaseFolder
    {
        static ADC_AutoTestingRepository instance = new ADC_AutoTestingRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ADC_AutoTestingRepository element repository.
        /// </summary>
        [RepositoryFolder("95f67aba-6c58-4884-bb87-3897faf7a665")]
        public static ADC_AutoTestingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ADC_AutoTestingRepository() 
            : base("ADC_AutoTestingRepository", "/", null, 0, false, "95f67aba-6c58-4884-bb87-3897faf7a665", ".\\RepositoryImages\\ADC_AutoTestingRepository95f67aba.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("95f67aba-6c58-4884-bb87-3897faf7a665")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class ADC_AutoTestingRepositoryFolders
    {
    }
#pragma warning restore 0436
}