///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADC_AUTO_Testing.Desktop_Apps.AD_MMC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Delete_User_boris5 recording.
    /// </summary>
    [TestModule("a1ebb38a-87f6-45b7-93d0-464a681a8fb4", ModuleType.Recording, 1)]
    public partial class Delete_User_boris5 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repository.
        /// </summary>
        public static ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repo = ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository.Instance;

        static Delete_User_boris5 instance = new Delete_User_boris5();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Delete_User_boris5()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Delete_User_boris5 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='abcd bbbb') on item 'AD_RNRX1_ONELOGIN.UserName'.", repo.AD_RNRX1_ONELOGIN.UserNameInfo, new RecordItemIndex(0));
            //Validate.Attribute(repo.AD_RNRX1_ONELOGIN.UserNameInfo, "Text", "abcd bbbb");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AD_RNRX1_ONELOGIN.UserName' at Center.", repo.AD_RNRX1_ONELOGIN.UserNameInfo, new RecordItemIndex(1));
            //repo.AD_RNRX1_ONELOGIN.UserName.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AD_RNRX1_ONELOGIN.Delete' at Center.", repo.AD_RNRX1_ONELOGIN.DeleteInfo, new RecordItemIndex(2));
            //repo.AD_RNRX1_ONELOGIN.Delete.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActiveDirectoryDomainServices.ButtonYes' at Center.", repo.ActiveDirectoryDomainServices.ButtonYesInfo, new RecordItemIndex(3));
            //repo.ActiveDirectoryDomainServices.ButtonYes.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Run application 'DeleteADUser_fromRNRX1.bat' with arguments '' in normal mode.", new RecordItemIndex(4));
            Host.Local.RunApplication("DeleteADUser_fromRNRX1.bat", "", "C:\\automation_ui\\AD_Suite\\", false);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
