///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADC_AUTO_Testing.Desktop_Apps.AD_MMC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_and_Verify_AD_Instance recording.
    /// </summary>
    [TestModule("7e863221-79bd-4637-93d5-39185052b625", ModuleType.Recording, 1)]
    public partial class Open_and_Verify_AD_Instance : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repository.
        /// </summary>
        public static ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repo = ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository.Instance;

        static Open_and_Verify_AD_Instance instance = new Open_and_Verify_AD_Instance();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_and_Verify_AD_Instance()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_and_Verify_AD_Instance Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // C:\source\AD_Suite
            Report.Log(ReportLevel.Info, "Application", "C:\\source\\AD_Suite\r\nRun application 'AD_Instance.msc' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("AD_Instance.msc", "", "C:\\automation_ui\\AD_Suite", false);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='rnrx1.onelogin') on item 'ADInstanceConsoleRoot.Rnrx1Onelogin'.", repo.ADInstanceConsoleRoot.Rnrx1OneloginInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.ADInstanceConsoleRoot.Rnrx1OneloginInfo, "Text", "rnrx1.onelogin");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='testOU1') on item 'ADInstanceConsoleRoot.TestOU11'.", repo.ADInstanceConsoleRoot.TestOU11Info, new RecordItemIndex(2));
            Validate.Attribute(repo.ADInstanceConsoleRoot.TestOU11Info, "Text", "testOU1");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Console Root') on item 'ADInstanceConsoleRoot.Tree.ConsoleRoot'.", repo.ADInstanceConsoleRoot.Tree.ConsoleRootInfo, new RecordItemIndex(3));
            //Validate.Attribute(repo.ADInstanceConsoleRoot.Tree.ConsoleRootInfo, "Text", "Console Root");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Active Directory Users and Computers [WIN-RERPJMAJ18I.borgrin.onelogin]') on item 'ADInstanceConsoleRoot.Tree.ActiveDirectoryUsersAndComputersWI'.", repo.ADInstanceConsoleRoot.Tree.ActiveDirectoryUsersAndComputersWIInfo, new RecordItemIndex(4));
            //Validate.Attribute(repo.ADInstanceConsoleRoot.Tree.ActiveDirectoryUsersAndComputersWIInfo, "Text", "Active Directory Users and Computers [WIN-RERPJMAJ18I.borgrin.onelogin]");
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
