///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ADC_AUTO_Testing.Desktop_Apps.AD_MMC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_ADStatus_Connected recording.
    /// </summary>
    [TestModule("20776f16-0b54-4844-953a-589dd01da553", ModuleType.Recording, 1)]
    public partial class Verify_ADStatus_Connected : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repository.
        /// </summary>
        public static ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository repo = ADC_AUTO_Testing.ALL_REPOS.AD_SuiteRepository.Instance;

        static Verify_ADStatus_Connected instance = new Verify_ADStatus_Connected();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_ADStatus_Connected()
        {
            var_Min_User_Count = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_ADStatus_Connected Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable var_Min_User_Count.
        /// </summary>
        [TestVariable("8801311a-5520-4619-bd2c-4ded43a1b7e1")]
        public string var_Min_User_Count
        {
            get { return repo.var_Min_User_Count; }
            set { repo.var_Min_User_Count = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Connected') on item 'OneLogin.DirectoriesPage.Connected'.", repo.OneLogin.DirectoriesPage.ConnectedInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.OneLogin.DirectoriesPage.ConnectedInfo, "InnerText", "Connected");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
