///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADC_AUTO_Testing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ADC_AUTO_TestingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("63141aed-73c7-46c8-a093-3e303566efe2")]
    public partial class ADC_AUTO_TestingRepository : RepoGenBaseFolder
    {
        static ADC_AUTO_TestingRepository instance = new ADC_AUTO_TestingRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ADC_AUTO_TestingRepository element repository.
        /// </summary>
        [RepositoryFolder("63141aed-73c7-46c8-a093-3e303566efe2")]
        public static ADC_AUTO_TestingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ADC_AUTO_TestingRepository() 
            : base("ADC_AUTO_TestingRepository", "/", null, 0, false, "63141aed-73c7-46c8-a093-3e303566efe2", ".\\RepositoryImages\\ADC_AUTO_TestingRepository63141aed.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("63141aed-73c7-46c8-a093-3e303566efe2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class ADC_AUTO_TestingRepositoryFolders
    {
    }
#pragma warning restore 0436
}