///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace ADC_AUTO_Testing.WebPages.Menu1_USERS.SubMenu4_Directories.Page_ActiveDirectory.Tab4_Advanced
{
    public partial class Provisioning_enabled_Uncheck
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Uncheck_Provisioning_enabled()
        {
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 100ms.");
            Delay.Duration(100, false);
            
            if (repo.OneLogin.LoginPage.DirectoryProvisioningEnabled.Checked=="True")
            {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OneLogin.LoginPage.ICheckHelper6' at Center.", repo.OneLogin.LoginPage.ICheckHelper1Info, new RecordItemIndex(1));
            repo.OneLogin.LoginPage.ICheckHelper6.Click();
            Delay.Milliseconds(200);
            }
        }

    }
}